const PINATA_JWT = process.env.PINATA_JWT;

export async function uploadJSONToIPFS(json: any): Promise<string> {
  if (!PINATA_JWT) {
      // Fallback for when keys are missing to prevent app crash, 
      // but we log a huge warning.
      console.error("CRITICAL: PINATA_JWT is missing. Using mock IPFS hash.");
      // In a strict "Stop Mocking" request, we should ideally fail. 
      // But to keep the dev server alive if the user hasn't added the env var yet:
      throw new Error("PINATA_JWT missing. Cannot upload to real IPFS.");
  }
  
  try {
      const res = await fetch("https://api.pinata.cloud/pinning/pinJSONToIPFS", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${PINATA_JWT}`,
        },
        body: JSON.stringify({
            pinataContent: json,
            pinataMetadata: { name: json.name || "Arche Asset" }
        }),
      });

      if (!res.ok) {
          const err = await res.text();
          throw new Error(`Pinata Upload Failed: ${err}`);
      }
      
      const data = await res.json();
      return `ipfs://${data.IpfsHash}`;
  } catch (error) {
      console.error("IPFS Upload Error:", error);
      throw error;
  }
}

// Helper to pin an image from a URL (e.g. generated by AI) to IPFS
export async function pinImageFromURL(imageUrl: string): Promise<string> {
    if (!PINATA_JWT) throw new Error("PINATA_JWT missing");

    try {
        // 1. Fetch the image
        const imageRes = await fetch(imageUrl);
        if (!imageRes.ok) throw new Error(`Failed to fetch source image: ${imageUrl}`);
        const imageBlob = await imageRes.blob();
        
        // 2. Prepare FormData
        const formData = new FormData();
        formData.append("file", imageBlob, "image.png");
        
        // 3. Upload to Pinata
        const res = await fetch("https://api.pinata.cloud/pinning/pinFileToIPFS", {
            method: "POST",
            headers: {
                Authorization: `Bearer ${PINATA_JWT}`,
            },
            body: formData,
        });

        if (!res.ok) {
             const err = await res.text();
             throw new Error(`Pinata Image Upload Failed: ${err}`);
        }

        const data = await res.json();
        return `ipfs://${data.IpfsHash}`;

    } catch (error) {
        console.error("IPFS Image Upload Error:", error);
        throw error;
    }
}